package:
    name: openmdao
    version: !!str 0.13.0

requirements:
    run:
        # Core
        - openmdao.lib ==0.13.0
        - openmdao.main ==0.13.0
        - openmdao.units ==0.13.0
        - openmdao.util ==0.13.0
        - openmdao.test ==0.13.0

        # Examples
        - openmdao.examples.bar3simulation ==0.13.0
        - openmdao.examples.expected_improvement ==0.13.0
        - openmdao.examples.mdao ==0.13.0
        - openmdao.examples.metamodel_tutorial ==0.13.0
        - openmdao.examples.nozzle_geometry_doe ==0.13.0
        - openmdao.examples.simple ==0.13.0

        # Fortran Extensions
        - cobyla ==1.0.2
        - conmin ==1.0.2
        - slsqp ==1.0.2
        - newsumt ==1.1.1

        # Dependencies
        - bson ==0.3.3
        - decorator >=3.4.0
        - docutils >=0.10
        - jinja2 >=2.4
        - mock >=1.0.1
        - networkx >=1.9.1
        - nose ==1.3.3
        - numpy >=1.7.1
        - pip
        - pycrypto ==2.3
        - pyevolve ==0.6
        - pyparsing >=1.5.7
        - pytz >=2014.4
        - requests ==2.2.1
        - scipy >=0.11
        - sphinx ==1.2.2
        - traits ==4.3.0
        - zope.interface >=3.6.1
